name: Release New Version
on:
  push:
    tags:
      - "*"

jobs:
  publish_containers:
    runs-on: ubuntu-latest
    permissions: write-all

    name: Publish Containers
    steps:
      - name: checkout
        uses: actions/checkout@v3.3.0
      - name: setup bun
        uses: "oven-sh/setup-bun@v2"
      - name: generate database
        run: "bun install && bun run generate"
      - name: log in to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: build and push
        run: ./scripts/publish-containers.sh ${{ github.ref_name }}



