name: test
on:
  push:
jobs:
  test-inkchat:
    name: Test Inkchat
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - run: ./scripts/test.sh

