<<<<<<< HEAD
name: test
on:
  push:
=======
name: Test Inkchat
>>>>>>> main
jobs:
  my-job:
    name: my-job
    runs-on: ubuntu-latest
    steps:
      # ...
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

<<<<<<< HEAD
      # run any `bun` or `bunx` command
      - run: bun install
      - run: ./scripts/test.sh
=======
      - run: bun install
      - run: cd apps/inkchat
      - run: bun test
>>>>>>> main
